### ISSUE TITLE
Option to generate flake attributes with cross-compilation enabled nixpkgs

### ISSUE THREAD

**Issue by ldesgoui** [hercules-ci/flake-parts#35]
Hello,

I've started playing with cross-compilation today, I tried to write an option similar to `perSystem` whose value would be called with each possible pair of `localSystem` and `crossSystem`, the goal would be to be able to write something like this:

```nix
{
  perCrossSystem = { pkgs, system, crossSystem, ... }: {
    packages."x/${crossSystem}/hello" = pkgs.hello;
  };
}
```

And get something like this:

```nix
{
  perSystem = { system, ... }: {
    packages."x/aarch64-linux/hello" = (import nixpkgs { inherit system; crossSystem = "aarch64-linux"; }).hello;
    packages."x/riscv64-linux/hello" = (import nixpkgs { inherit system; crossSystem = "riscv64-linux"; }).hello;
    packages."x/x86_64-linux/hello" = (import nixpkgs { inherit system; crossSystem = "x86_64-linux"; }).hello;
  };
}
```

I have some basic knowledge of developing NixOS modules but I had a very hard time understanding how `perSystem` works, could you throw me a few pointers?
What I've tried so far was just defining an option of type `raw` and using it in something like `config.perSystem = { system, ... }: lib.mkMerge (map (crossSystem: config.perCrossSystem { pkgs = import nixpkgs { inherit system crossSystem; }; }) config.systems);`, but that recurses infinitely.

Side note, `functionTo` in `lib.nix` doesn't seem to be used anymore.

Thanks for this library, it's a pleasure to work with.

**Comment by roberth** [comment]
This could be generalized to arbitrary variants of the flake configuration.
1. move this to flake-parts https://github.com/hercules-ci/hercules-ci-agent/blob/master/variants.nix
2. add cross compilation option for setting Nixpkgs `buildPlatform` (setting `crossSystem` is wrong imo)
3. add renaming functions and options to control the copying of attributes from the otherwise invisible `variants.<x>.packages.<y>` to `packages."${x}/${y}"`

An alternative solution for adding cross support could be https://github.com/NixOS/nixpkgs/pull/160061.

I am not aware of any documentation regarding cross compilation with flakes. Are you?
I would expect packages in `packages.<system>` to be runnable on _system_, as suggested by the `nix run` behavior. Ultimately Nix is all about outputs, as those are the usable end product. Where the derivation runs is secondary and is abstracted away by the remote builder concept.

That is the nature of cross compilation, but the Nix CLI behavior seems to steer towards a solution that repeats the mistakes of `nixos/modules/misc/nixpkgs.nix`.

**Comment by ldesgoui** [comment]
Hey,

Thanks a lot for the pointers, it did allow me to figure it out, here's how that looks like for now

```nix
{ config, inputs, ... }:
let
  rootConfig = config;
in
{
  perSystem = { config, lib, system, moduleType, ... }: {
    options =
      let
        inherit (lib) mkOption types;
      in
      {
        crossSystems = mkOption {
          type = types.listOf types.str;

          default = builtins.filter (c: system != c && config.selectCrossSystem c) rootConfig.systems;
        };

        selectCrossSystem = mkOption {
          type = types.functionTo types.bool;

          default = crossSystem:
            let
              local = lib.systems.elaborate system;
              cross = lib.systems.elaborate crossSystem;
            in
            # Can only build MacOS stuff from MacOS
            (cross.isMacOS -> local.isMacOS)
            # https://github.com/NixOS/nixpkgs/issues/137877
            && (local.isMacOS && local.isAarch64 -> !cross.isLinux)
          ;
        };

        x = mkOption {
          type = types.lazyAttrsOf moduleType;
          default = { };
        };
      };

    config = {
      _module.args.pkgs = lib.mkIf (config ? _module.args.crossSystem)
        (import inputs.nixpkgs {
          inherit system;
          inherit (config._module.args) crossSystem;
        });

      x = lib.mkIf (!(config ? _module.args.crossSystem))
        (lib.genAttrs config.crossSystems (c: { _module.args.crossSystem = c; }));
    };
  };
}
```

> add cross compilation option for setting Nixpkgs `buildPlatform` (setting `crossSystem` is wrong imo)

I looked far and wide, that seems to only be a NixOS thing

> I am not aware of any documentation regarding cross compilation with flakes [..]

Yeah, this is a bit of a philosophical question that I chose not to find an answer to :P
Feels like `packages.<system>` should be buildable on `<system>` and `apps.<system>` should be runnable on `<system>`, and all package shouldn't implicitly be apps?
