### ISSUE TITLE
Allow for more more than just packages in `perSystem.packages`

### ISSUE THREAD

**Issue by MagicRB** [hercules-ci/flake-parts#44]
https://github.com/hercules-ci/flake-parts/blob/main/modules/packages.nix#L31 there the type of `perSystem.packages` is restricted to `lazyAttrsOf package`, which mostly is fine, but just in nixpkgs we have examples which won't fit there, namely `generators` or `writeText`. In my flake I define custom helpers of both the `attrsetOf (attrsOf package)` and `attrsetOf function` nature. I propose a new type:
```nix
let
  self = 
    oneOf
      [ (lazyAttrsOf self)
        package
        (functionTo self)
      ];
in
  lazyAttrsOf self // { description = "Attrs of functions or packges, with arbitrary depth."; }
```

**Comment by MagicRB** [comment]
i just figured out that `flake check` doesn't like non derivation things in `packages`, so technically flake-parts is correct here. It's weird that Nix doesn't accept this. but that has to be dealt with first.

**Comment by roberth** [comment]
I think I was typing my reply to the PR while you wrote this.

I'd like `packages` to be a tree of packages too. I know restricting packages was a conscious choice to fight the mess that is, say, Nixpkgs top-level. Having to peek into each attribute value to figure out the type can restrict the implementation freedom of tooling and therefore tooling quality. Or at least, that's a rough sketch of the problem.

Example problem: listing all packages

Current solution, as Nix equivalent: `attrNames packages.${currentSystem}`

Proposed solution, pseudocode `filterTree isPackage (traverseAttrs packages.${currentSystem})`

The extra complexity is worth its bits in megabytes for expression writing, but the new solution is strict in the `attrValues` of `packages.${currentSystem}`. This is bad for performance because now it has to actually evaluate those package definitions, at least up to `attrNames pkg` and `pkg.type`.
