### ISSUE TITLE
Unable to add package with unfree license to `packages` output

### ISSUE THREAD

**Issue by montchr** [hercules-ci/flake-parts#55]
I have a custom package defined in my configuration repo for an ancient Epson printer driver with a partially-unfree license:

https://github.com/montchr/dotfield/blob/flake-parts-v3/packages/drivers/epson_201212w/default.nix

I'm adding this package to my `packages` output via `perSystem.packages.epson_201212w`.

Upon running `nix flake check`, however, evaluation fails because this package uses an unfree license.

Is there any way to provide this package as a flake output without causing checks to fail?

I could see the sense in flakes disallowing this entirely for the sake of respecting purity (i.e. ignoring my system configuration's `nixpkgs.config.allowUnfree` setting) and enforcing the safe default of disallowing redistribution of unfree packages. Like, if providing this package in flake outputs means that any user of my flake will automatically become a copyright infringer :upside_down_face: I just want my printer to work on NixOS.

On the other hand, this package is essentially the same as [a similar driver in Nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/drivers/epson_201207w/default.nix), though I don't think that the existing driver would support my printer. So, given that Nixpkgs does provide packages for unfree software, maybe it's not inherently wrong for my flake to do so also...?

**Comment by montchr** [comment]
All that said, I can work around the issue with `flake-utils.lib.filterPackages`.

https://github.com/montchr/dotfield/commit/9fa6a07cd3ab7f78e45555f3ed11ad3957f0157d

```patch
diff --git a/packages/default.nix b/packages/default.nix
index f0d78866..41f9d9ce 100644
--- a/packages/default.nix
+++ b/packages/default.nix
@@ -1,5 +1,6 @@
 {self, ...}: let
   inherit (self) inputs;
+  inherit (inputs.flake-utils.lib) filterPackages;
   inherit (inputs.gitignore.lib) gitignoreSource;
   inherit
     (builtins)
@@ -79,6 +80,7 @@ in {
   };
   perSystem = ctx @ {
     pkgs,
+    system,
     config,
     inputs',
     ...
@@ -87,6 +89,6 @@ in {
   in {
     # TODO: remove the need for sources outside of this flake module -- package everything beforehand
     _module.args.sources = sources;
-    packages = dotfieldPackages pkgs;
+    packages = filterPackages system (dotfieldPackages pkgs);
   };
 }
```

**Comment by montchr** [comment]
Also, related: I've also resorted to using `filterPackages` for packages which are only supported on Darwin (e.g. `yabai`) -- this step seems necessary, unfortunately, because `perSystem` does not (correct me if I'm wrong) allow for specifying a subset of the systems in `config.systems`.

**Comment by roberth** [comment]
I plan to add an optional module for initializing a custom `pkgs`, allowing `allowUnfree` to be set, etc. This should be ok, as long as you don't distribute binaries with, for example, a public binary cache. (Not legal advice)
Meanwhile, you can do this yourself by setting `_module.args.pkgs = import nixpkgs { inherit system; config.allowUnfree = true; }` in your `perSystem` module.

> resorted to using `filterPackages`


_By default_, flake-parts won't do any filtering, because it reduces laziness, as `filterAttrs (k: v: f v)` for non-trivial `f` can't return an attribute set of thunks before the `f` has forced the values. It slows down the case where you only need a single attribute to be evaluated.
It would be nice to facilitate filtering at the very last moment, so that `packages` can keep referencing other `config.packages` (without recursion, but with performance loss).
It would also be nice to facilitate filtering by attribute name only.


> because `perSystem` does not (correct me if I'm wrong) allow for specifying a subset of the systems in `config.systems`.

If you want to ignore whole systems, you can do so in `config.systems`. If you want to omit certain attributes, you can use the `system` module argument like you show in the diff above.

I don't think I understand what you had in mind. Would it be similar to setting (top-level) `flake.packages.x86_64-linux.foo = lib.mkForce null`? (Although `null` is also not valid according to `nix flake check` iirc)

**Comment by montchr** [comment]
I think, at the time of writing, I was only applying `config.allowUnfree` to my system configurations but not the instance of `nixpkgs` used at the top level of my flake.

> Meanwhile, you can do this yourself by setting `_module.args.pkgs = import nixpkgs { inherit system; config.allowUnfree = true; }` in your `perSystem` module.

Exactly, yeah, that worked. Thanks!
